import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import StoreProvider from 'src/app/StoreProvider'
import { TypeUtils } from 'src/util/common/TypeUtils'
import Puro = TypeUtils.Puro

const interFont = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}



type RootProps = Puro<{
  children: React.ReactNode
}>

const Root =
React.memo(
(props: RootProps) => {
  return <StoreProvider>
    <RootLayout>
      {props.children}
    </RootLayout>
  </StoreProvider>
})
export default Root




type RootLayoutProps = Puro<{
  children: React.ReactNode
}>

const RootLayout =
React.memo(
(props: RootLayoutProps) => {
  
  return <html lang="en">
    <body className={interFont.className}>
      {props.children}
    </body>
  </html>
})
