import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import StoreProvider from 'src/app/StoreProvider'
import { Good } from 'src/model/Good'
import { ChildrenProps } from 'src/util/react/ChildrenProps'


const interFont = Inter({ subsets: ["latin"] })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}





const Root =
React.memo(
async (props: ChildrenProps) => {
  
  const goods = await fetchAsyncGoods()
  
  return <StoreProvider initialGoods={goods}>
    <RootLayout>
      {props.children}
    </RootLayout>
  </StoreProvider>
})
export default Root





const RootLayout =
React.memo(
(props: ChildrenProps) => {
  
  return <html lang="en">
    <body className={interFont.className}>
      {props.children}
    </body>
  </html>
})







async function fetchAsyncGoods(): Promise<Good[]> {
  return new Promise((res, rej) => setTimeout(
    () => res(goodsToFetchAsync),
    10000
  ))
}



const goodsToFetchAsync: Good[] = [
  {
    id: 'triangle',
    name: 'Cube',
    type: 'geometric figure',
    price: '100',
    description: 'This unique art object personifies the three-dimensionality of space',
  },
  {
    id: 'table',
    name: 'Table',
    type: 'furniture',
    price: '40',
    description: 'Table with intricate design',
  },
  {
    id: 'sphere',
    name: 'Sphere',
    type: 'geometric figure',
    price: '80',
    description: 'It is round from any side',
  },
  {
    id: 'wardrobe',
    name: 'Wardrobe',
    type: 'furniture',
    price: '200',
    description: 'This wardrobe leads to Narnia',
  },
]
