import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import StoreProvider from 'src/app/StoreProvider'
import { ChildrenProps } from 'src/util/react/ChildrenProps'


const interFont = Inter({ subsets: ["latin"] })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}





const Root =
React.memo(
(props: ChildrenProps) => {
  return <StoreProvider>
    <RootLayout>
      {props.children}
    </RootLayout>
  </StoreProvider>
})
export default Root





const RootLayout =
React.memo(
(props: ChildrenProps) => {
  
  return <html lang="en">
    <body className={interFont.className}>
      {props.children}
    </body>
  </html>
})
